# Monte Carlo evaluation and Comparsions to other software

Before applying our methodology to real data simulation, we conduct several Monte Carlo studies to investigate method performance in comparison to other existing implementations. We focus the numerical experiments on assessing how well the procedure scales to high dimension with respect to reasonable computation times (property S1 above) and accurately matching marginal and dependency parameters. The simulations will proceed in increasing complexity --- leading up to the setting in our motivating example. We begin by exploring simple exchangeable (constant) correlation structures under a large number of simulation replicates while applying the algorithm above to first continuous then discrete marginal distributions. We conclude the simulation studies with $10^5$ replicated data sets with sample sizes and distributional characteristics corresponding the estimates from the motivating example data.

The CPU-based computation times we report were from runs using eight dual-threaded 3.9GHz
Xeon Gold processors on a linux workstation, allowing for parallel instructions
over 16 cores. We chose 15 cores for our experiments.

## Other multivariate simulation software

Describe the competing software and algorithms briefly.

- `copula`
- `Genord`
- `Multiord`
- `nortaRA` only does Pearson matching.

## Simulation I: Bivariate simulation using rank-based correlation

### Continuous example: Bivariate Exponential

Both Spearman's and Kendall's measures of dependency are invariant under
strictly monotone transformations (ref). This in turn provides exact simulation
of continuous marginals $F_i$ $i=1,\ldots,d$ since their corresponding quantile
function are increasing monotonically over their support. The results below
provide computations times for $N=10^5$ under increasingly large dimension $d$.
For simplicity we assume multivariate Normal with varying parameters and to
additionally demonstrate the utility of Kendall's $\tau$ even in the Gaussian
setting (as opposed to the nature choice of Pearson's correlation). To layer on complexity, we now assume a multivariate gamma distribution with fixed marginal parameters.

Compare speed and accuracy.

```{r tabGamma, echo = TRUE}
## computation times normal

```
### Discrete example: Bivariate Geometric

Compare speed and accuracy.

## Simulation II: Ultra HD multivariate simulation with identical margins and exchangeable rank-based correlation. 

### UHD Continuous example: Multivariate Gamma

Compare speed and accuracy.

### UHD Discrete example: Multivariate Negative Binomial

Compare speed and accuracy.

## Simulation III: Ultra HD multivariate simulatino with heterogenous margins and exchangeable rank-based correlation. 

### UHD Heteregeous continuous example: Multivariate Gamma

Compare speed and accuracy.

### UHD Heteregeousdiscrete example: Multivariate Negative Binomial

Compare speed and accuracy.
