---
documentclass: jss
author:
  - name: Alfred G. Schissler
    affiliation: University of Nevada
    address: |
      | 1664 N Virginia St.
      | Reno, NV 89557
    email: \email{aschissler@unr.edu}
  - name: Edward J. Bedrick
    affiliation: University of Arizona
  - name: Alexander D. Knudson
    affiliation: University of Nevada \AND
  - name: Tomasz J. Kozubowski
    affiliation: University of Nevada
  - name: Tin Nguyen
    affiliation: University of Nevada
  - name: Anna K. Panorska
    affiliation: University of Nevada \AND
  - name: Juli Petereit
    affiliation: University of Nevada
  - name: Walter W. Piegorsch
    affiliation: University of Arizona
  - name: Duc Tran
    affiliation: University of Nevada
title:
  formatted: "Simulating High-Dimensional Multivariate Data using the \\pkg{Bigsimr} Package"
  plain:     "Simulating High-Dimensional Multivariate Data using the Bigsimr Package"
  short:     "\\pkg{Bigsimr}: Simulate High-Dimensional Multivariate Data"
abstract: >
  It is critical to accurately simulate data when employing Monte Carlo techniques and evaluating statistical methodology. Measurements are often correlated and high dimensional in this era of big data, such as data obtained in high-throughput biomedical experiments. Due to the computational complexity and a lack of user-friendly software available to simulate these massive multivariate constructions, researchers resort to simulation designs that posit independence or perform arbitrary data transformations. To close this gap, we developed the \pkg{Bigsimr} Julia package with R and Python interfaces. These packages empower high-dimensional random vector simulation with arbitrary marginal distributions and dependency via a Pearson, Spearman, or Kendall correlation matrix. \pkg{Bigsimr} contains high-performance features, including multi-core and graphical-processing-unit-accelerated algorithms to estimate correlation and compute the nearest correlation matrix. Monte Carlo studies quantify the accuracy and scalability of our approach, up to $d=10,000$. We describe example workflows and apply to a high-dimensional data set --- RNA-sequencing data obtained from breast cancer tumor samples.
keywords:
  formatted: [multivariate simulation, high-dimensional data, nonparametric correlation, Gaussian copula, RNA-sequencing data, breast cancer]
  plain:     [multivariate simulation, high-dimensional data, nonparametric correlation, Gaussian copula, RNA-sequencing data, breast cancer]
preamble: >
  \usepackage{amsmath}
output: rticles::jss_article
bibliography: [bigsimr.bib, packages.bib, alex.bib]
---

```{r, setup, include=FALSE}
options(prompt = 'R> ', continue = '+ ')
```

\clearpage

# Introduction

Massive high-dimensional (HD) data sets are now common in many areas of scientific inquiry. As new methods are developed for data analysis, a fundamental challenge lies in designing and conducting simulation studies to assess the operating characteristics of proposed methodology --- such as false positive rates, statistical power, interval coverage, and robustness. Further, efficient simulation empowers statistical computing strategies, such as the parametric bootstrap [@Chernick2008] to simulate from a hypothesized null model, providing inference in analytically challenging settings. Such Monte Carlo (MC) techniques become difficult for HD dependent data using existing algorithms and tools. This is particularly true when simulating massive multivariate, non-normal distributions, arising in many fields of study.

As others have noted, it can be vexing to simulate dependent, non-normal/discrete data, even for low-dimensional (LD) settings [@MB13; @XZ19]. For continuous non-normal LD multivariate data, the well-known NORmal To Anything (NORTA) algorithm [@Cario1997] and other copula approaches [@Nelsen2007] are well-studied and implemented in publicly-available software [@Yan2007; @Chen2001]. Yet these approaches do not scale in a timely fashion to HD problems [@Li2019gpu]. For discrete data, early simulation strategies had major flaws, such as failing to obtain the full range of possible correlations --- such as admitting only positive correlations [@Park1996]. While more recent approaches [@MB13; @Xia17; @BF17] have remedied this issue for LD problems, the existing tools are not designed to scale to high dimensions.

Another central issue lies in characterizing dependence between components in the HD random vector. The choice of correlation in practice usually relates to the eventual analytic goal and distributional assumptions of the data (e.g., non-normal, discrete, infinite support, etc.). For normal data, the Pearson product-moment correlation describes the dependence perfectly. However, simulating arbitrary random vectors that match a target Pearson correlation matrix is computationally intense [@Chen2001; @Xia17]. On the other hand, an analyst might consider use of nonparametric correlation measures to better characterize monotone, non-linear dependence, such as Spearman's $\rho$ and Kendall's $\tau$. Throughout, we focus on matching these nonparametric dependence measures, as our aim lies in modeling non-normal data and these rank-based measures possess invariance properties enabling our proposed methodology. We do, however, implement Pearson matching, but several layers of approximation are required.

With all this in mind, we present a scalable, flexible multivariate simulation algorithm. The crux of the method lies in the construction of a Gaussian copula in the spirit of the NORTA procedure. As we will describe in more detail, the algorithm's design leverages useful properties of nonparametric correlation measures, namely invariance under monotone transformation and well-known closed-form relationships between dependence measures for the multivariate normal (MVN) distribution. For our method, we developed a high-performance implementation: the `Bigsimr` Julia package, with R and Python interfaces `bigsimr`.

This article proceeds by providing background information, including a description of a motivating example application: RNA-sequencing (RNA-seq) breast cancer data. Then we describe and justify our simulation methodology and related algorithms. We proceed by providing an illustrative LD `bigsimr` workflow. Next we conduct MC studies under various bivariate distributional assumptions to evaluate performance and accuracy. After the MC evaluations, we simulate random vectors motivated by our RNA-seq example, evaluate the accuracy, and provide example statistical computing tasks, namely MC estimation of joint probabilities and evaluating HD correlation estimation efficiency. Finally, we discuss the method's utility, limitations, and future directions.
